spring.datasource.url=jdbc:postgresql://dpg-ct1s3b56l47c73bi9q0g-a.oregon-postgres.render.com:5432/basedssd_737y
spring.datasource.username=basedssd_737y_user
spring.datasource.password=qYdabDp7Gs2mBTX80occV1IjmdlAwwah
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
security.jwt.expiration-time=3600000